### ISSUE TITLE
50Hz observations

### ISSUE THREAD

**Issue by behinger** [s-ccs/project-eegManyPipelines#23]
Starting from 1601 => which is subject 16
`1801` has 10 components removed

## Todo:
to exclude that the noise comes from the reference-channel:
- take a late subject
- run average reference first
- rerun zapline and post the output plot here

**Comment by behinger** [comment]
`1801`
![grafik](https://user-images.githubusercontent.com/10183650/159260488-a61cc8ed-6eeb-4eb2-92fa-c0a361d3cabb.png)

**Comment by ReneSkukies** [comment]
Subject 18 dropped because of faulty Electrode F6
![image](https://user-images.githubusercontent.com/57703446/159265353-f62fd1e8-7f76-4536-8920-daeb21e80eda.png)

**Comment by behinger** [comment]
Closing this for now; we can reopen it, in case we observe further Line-Noise issues.

Marius (Zapline-Plus) mentioned that our results look reasonable and he would not fiddle with the parameters
